### ISSUE TITLE
Option to switch Razer logo and gaming mode on/off

### ISSUE THREAD

**Issue by jt1900jt** [reven/razer-osx-led-gui#1]
the osx-razer-led port supports controlling the logo on the back of the laptop and I'm hoping you can integrate that into this gui. I also found another port of this that allows for enabling and disabling razors "gaming mode" (really it just boosts the cpu clock) that I edited and mess around with. 
[Attached here](https://github.com/reven/razer-osx-led-gui/files/4625859/Archive.zip)

Unfortunately I can't remember exactly which repo I got this from and I can't seem to track it down. The above are just executables but maybe you can do something with them.

**Comment by reven** [comment]
Hey,

Ok, I had no idea what the 'logo' option did, but I guess that makes sense! I can definately try to add that back in.

The gaming mode is a whole other beast. I can't do much with the executables, but anyway I don't think it fits in very well with the app or the underlying driver, sorry.

Give me a few days for the logo.

**Comment by reven** [comment]
Ok, so that wasn't actually a lot to get it back in there. Let me know if it works, as I can't test this functionality.

**Comment by jt1900jt** [comment]
works like a charm! thanks so much for all the work on this! i've been trying to find an application to do this without having to revert to the terminal. I have one more request that probably isn't within the scope of this but I figured if you had any ideas on how to do this. 

would it be possible to remap the f10/f11 keys (the ones that control keyboard brightness in windows) to increase and decrease the brightness? I'm currently doing this by with two automator scripts (basically it just called the osx-razer-led and runs the brightness up/down command) that I wrote and converted to apps and then invoke through [this](https://github.com/deseven/icanhazshortcut). Its extremely inefficient and slightly buggy. Ill attach the automator apps I'm using below.
[Archive.zip](https://github.com/reven/razer-osx-led-gui/files/4626090/Archive.zip)
Also I managed to track down the official project that gaming mode was a part of! It was actually on an old backup I had lying around. I'm not even entirely sure if its working properly. I'll have to do some benchmarking to see if the cpu truly is boosting. Here is the snippet of code that has it if you're interested.  
![Screen Shot 2020-05-13 at 9 45 38 PM](https://user-images.githubusercontent.com/54914476/81893801-37482f80-9563-11ea-88dd-796b48bfdb1a.png)

**Comment by reven** [comment]
Hey,

So the keyboard brightness keys (f10 and f11) work out of the box, at least on my Stealth. Just press them in combination to the fn key and they should do their thing. They're not recognized by MacOS, so the keyboard brightness icon doesn't come up, but they still work. That's the thing, the keyboard and the USB device that control it have some weird quirks and they seem to override a lot of things in the background, that's why re-mapping keys is a nightmare. I use Karabiner-Elements but I haven't been able to get the function keys to work as their "special" values in order to not have to press the fn key to change volume, brightness, etc. I can remap some of them, but MacOS can't detect the fn press, at least on my system. Anyway, we probably don't have the same system, but keyboard brightness keys should work out of the box if everything is patched up correctly.

Another thought: from the snippet of code in the image, I don't think that is doing anything to change the CPU; it's just doing a "gaming" effect on the keyboard, which I assume is lighting red WASD keys or something like that. I've seen that effect in a few places, but on the Stealth the whole keyboard has to be the same color, so again, no way to test that.

Hope that helps.
